### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by lemon-prog123** [simonefelicioni/InteractionGCN#1]
Hi ! I have read your paper. And I'm interested in the part of gaze estimation. Where can I find the release code?

**Comment by simonefelicioni** [comment]
Hello. Unluckily, the code is not ready for being shared yet, since we are working on an extension of the proposed approach. In a few months, I hope there will be an updated version of the paper and the code.

Anyway, if you are interested in the gaze estimation part, some details may be found in the current paper. In particular, we assumed that the gaze direction is coherent with the 3D head orientation. People's gazes may be described as a cone in 3D space with a certain angle, so that a person V is looking at someone else R if R’s head point in 3D space belongs to the cone built from V’s head orientation.

In more detail, our approach is based on the following algorithm:
1. Define a unit vector u, which points along the axis of the cone (i.e. the first person line of sight based on his head orientation).
2. Define vector vr which points from the cone vertex V to the point in question R.
3. Take the dot product vr · u. This value represents the cosine of the angle between vr and u.
4. Take the arc cosine of the value calculated in 3. If the resulting angle is larger than the cone angle, the point is outside the cone.

Hope it could help. Please, feel free to reach me out if there are still other concerns or doubts.
